---
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: claude_apu
  annotations:
    - title: "Claude Sonnet 3.5"
spec:
  implementation: APU
  audio_unit: OpenAiSpeech
  image_unit: OpenAIImageUnit
  llm_unit:
    implementation: AnthropicLLMUnit
    model: "claude-3-5-sonnet-20240620"
---
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: claude-3-5-sonnet-20240620
spec:
  implementation: LLMModel
  human_name: Claude Sonnet 3.5
  name: "claude-3-5-sonnet-20240620"
  input_context_limit: 200000
  output_context_limit: 8192
  supports_tools: True
  supports_image_input: True
  supports_audio_input: False
