apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: repo_code_search

spec:
  implementation: RetrieverAgent
  apu: claude_apu
  name: "code_search"
  description: "Search the github repository for code. This agent can only search for .python, .js, .jsx, .ts, and .tsx files (i.e. code files) and cannot search for document that is not in the code."
  document_manager:
    loader:
      implementation: GitHubLoader
      owner: "eidolon-ai"
      repo: "eidolon"
      pattern:
        - "**/*.py"
        - "**/*.js"
        - "**/*.jsx"
        - "**/*.ts"
        - "**/*.tsx"
