apiVersion: eidolon/v1
kind: Agent
metadata:
  name: repo_doc_search

spec:
  implementation: RetrieverAgent
  apu: claude_apu
  name: "doc_search"
  description: "Search the github repository for documentation. This agent can only search for .md files (i.e. documentation files) and cannot search for code."
  document_manager:
    loader:
      implementation: GitHubLoader
      owner: "eidolon-ai"
      repo: "eidolon"
      pattern:
        - "**/*.md"
      exclude: "**/test/**/*"
